on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/edgelesssys/ego-dev

    steps:
      - uses: actions/checkout@v4
      - run: ego-go test -c ./internal/edg
      - run: ego sign edg.test
      - run: ego run edg.test
        env:
          OE_SIMULATION: "1"
